services:
  resume-matcher:
      image : resume-matcher
      build:
        context: ./
        dockerfile : build.dockerfile
      ports:
        - 80:8501
      
      volumes:
        - ./Data/Resumes:/data/Resume-Matcher/Data/Resumes
        - ./Data/Processed:/data/Resume-Matcher/Data/Processed
